"""Add garage display settings to User model

Revision ID: 008bd7bcf7a1
Revises: cd3f0707d765
Create Date: 2025-10-05 01:07:29.265627

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '008bd7bcf7a1'
down_revision = 'cd3f0707d765'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('garage_display_settings', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False, comment='ガレージカードの表示項目設定'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('garage_display_settings')

    # ### end Alembic commands ###
