"""Add event relation for note

Revision ID: 0529862eafb8
Revises: 3e619e397d02
Create Date: 2026-04-21 22:19:01.833864

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0529862eafb8'
down_revision = '3e619e397d02'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('general_notes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('event_id', sa.Integer(), nullable=True, comment='紐付けるイベントのID'))
        batch_op.create_index(batch_op.f('ix_general_notes_event_id'), ['event_id'], unique=False)
        batch_op.create_foreign_key(None, 'events', ['event_id'], ['id'], ondelete='SET NULL')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('general_notes', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_general_notes_event_id'))
        batch_op.drop_column('event_id')

    # ### end Alembic commands ###
