"""Add is_pinned to GeneralNote

Revision ID: 079d7fe7cb3e
Revises: 661acfdfe77c
Create Date: 2026-01-29 05:21:52.045442

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '079d7fe7cb3e'
down_revision = '661acfdfe77c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('general_notes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_pinned', sa.Boolean(), server_default='false', nullable=False))
        batch_op.create_index(batch_op.f('ix_general_notes_is_pinned'), ['is_pinned'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('general_notes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_general_notes_is_pinned'))
        batch_op.drop_column('is_pinned')

    # ### end Alembic commands ###
