"""Add TrackSchedule model

Revision ID: 19f355eab962
Revises: 92c294d8d5dd
Create Date: 2025-12-01 02:19:30.566054

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '19f355eab962'
down_revision = '92c294d8d5dd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('track_schedules',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('circuit_name', sa.String(length=150), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('start_time', sa.Time(), nullable=True),
    sa.Column('end_time', sa.Time(), nullable=True),
    sa.Column('title', sa.String(length=100), nullable=False, comment='走行枠名 (例: 2S, R1, 大型枠)'),
    sa.Column('notes', sa.String(length=200), nullable=True, comment='クラス分けや資格などの補足'),
    sa.Column('source_url', sa.String(length=2048), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('circuit_name', 'date', 'start_time', 'title', name='uq_track_schedule')
    )
    with op.batch_alter_table('track_schedules', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_track_schedules_circuit_name'), ['circuit_name'], unique=False)
        batch_op.create_index(batch_op.f('ix_track_schedules_date'), ['date'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('track_schedules', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_track_schedules_date'))
        batch_op.drop_index(batch_op.f('ix_track_schedules_circuit_name'))

    op.drop_table('track_schedules')
    # ### end Alembic commands ###
