"""Add avatar_url to User model

Revision ID: 2611ecc6c187
Revises: c9271122696a
Create Date: 2025-07-15 16:05:25.737964

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2611ecc6c187'
down_revision = 'c9271122696a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('avatar_url', sa.String(length=2048), nullable=True, comment='MisskeyのアバターURL'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('avatar_url')

    # ### end Alembic commands ###
