"""Add has_completed_tutorial to User model

Revision ID: 2b2e0801467f
Revises: cd8c6f685e48
Create Date: 2025-09-26 01:39:22.651265

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '2b2e0801467f'
down_revision = 'cd8c6f685e48'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('completed_tutorials', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False, comment="完了したチュートリアルのキーを格納する (例: {'initial_setup': true})"))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('completed_tutorials')

    # ### end Alembic commands ###
