"""Add primary and gear ratios to Motorcycle

Revision ID: 309af67c371a
Revises: e41c7c921b61
Create Date: 2025-09-04 01:30:40.664060

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '309af67c371a'
down_revision = 'e41c7c921b61'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('motorcycles', schema=None) as batch_op:
        batch_op.add_column(sa.Column('primary_ratio', sa.Numeric(precision=7, scale=4), nullable=True, comment='一次減速比'))
        batch_op.add_column(sa.Column('gear_ratios', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment="各ギアの変速比 (例: {'1': 2.846, '2': 2.000, ...})"))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('motorcycles', schema=None) as batch_op:
        batch_op.drop_column('gear_ratios')
        batch_op.drop_column('primary_ratio')

    # ### end Alembic commands ###
