"""Add garage card fields to Motorcycle

Revision ID: 37af33cd44be
Revises: 7b1844b671ec
Create Date: 2025-08-07 12:28:52.906950

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '37af33cd44be'
down_revision = '7b1844b671ec'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('motorcycles', schema=None) as batch_op:
        batch_op.add_column(sa.Column('public_id', sa.String(length=36), nullable=True, comment='公開用の一意なID'))
        batch_op.add_column(sa.Column('is_public', sa.Boolean(), server_default='false', nullable=False, comment='ガレージカードを公開するか'))
        batch_op.add_column(sa.Column('image_url', sa.String(length=2048), nullable=True, comment='車両画像のURL'))
        batch_op.add_column(sa.Column('custom_details', sa.Text(), nullable=True, comment='カスタム箇所のメモ'))
        batch_op.create_index(batch_op.f('ix_motorcycles_public_id'), ['public_id'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('motorcycles', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_motorcycles_public_id'))
        batch_op.drop_column('custom_details')
        batch_op.drop_column('image_url')
        batch_op.drop_column('is_public')
        batch_op.drop_column('public_id')

    # ### end Alembic commands ###
