"""Add exclude_from_average to fuel_entries

Revision ID: 3c3d01d7c4c9
Revises: 6dadc8ff0649
Create Date: 2025-06-24 00:47:43.926517

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3c3d01d7c4c9'
down_revision = '6dadc8ff0649'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('fuel_entries', schema=None) as batch_op:
        batch_op.add_column(sa.Column('exclude_from_average', sa.Boolean(), server_default='false', nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('fuel_entries', schema=None) as batch_op:
        batch_op.drop_column('exclude_from_average')

    # ### end Alembic commands ###
