"""Add bot_notification_logs table

Revision ID: 3e619e397d02
Revises: 6822ab0afd37
Create Date: 2026-04-14 13:10:39.920643

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '3e619e397d02'
down_revision = '6822ab0afd37'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bot_notification_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('notification_type', sa.String(length=100), nullable=False, comment="通知タイプ (例: 'event_60days_123', 'leaderboard_record_456')"),
    sa.Column('event_id', sa.Integer(), nullable=True, comment='関連するイベントID（イベント通知の場合）'),
    sa.Column('misskey_note_id', sa.String(length=32), nullable=True, comment='投稿のノートID'),
    sa.Column('posted_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('bot_notification_logs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_bot_notification_logs_notification_type'), ['notification_type'], unique=True)

    with op.batch_alter_table('event_notifications', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_event_notifications_event_id'))

    op.drop_table('event_notifications')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('event_notifications',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('event_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('notification_type', sa.VARCHAR(length=50), autoincrement=False, nullable=False, comment="通知タイプ (例: '60days', '30days', '14days', '7days', '3days', '1day', 'today')"),
    sa.Column('misskey_note_id', sa.VARCHAR(length=32), autoincrement=False, nullable=True, comment='投稿のノートID'),
    sa.Column('posted_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], name=op.f('event_notifications_event_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('event_notifications_pkey')),
    sa.UniqueConstraint('event_id', 'notification_type', name=op.f('uq_event_notification_type'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    with op.batch_alter_table('event_notifications', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_event_notifications_event_id'), ['event_id'], unique=False)

    with op.batch_alter_table('bot_notification_logs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_bot_notification_logs_notification_type'))

    op.drop_table('bot_notification_logs')
    # ### end Alembic commands ###
