"""Add activity log models

Revision ID: 3f7f9b1139eb
Revises: 48c543b24155
Create Date: 2025-07-05 10:24:44.628235

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3f7f9b1139eb'
down_revision = '48c543b24155'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('activity_logs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('activity_title', sa.String(length=200), nullable=True, comment='活動名 (例: 7月の走行会)'))
        batch_op.add_column(sa.Column('location_type', sa.String(length=20), nullable=True, comment='場所の種別 (例: circuit, custom)'))
        batch_op.add_column(sa.Column('circuit_name', sa.String(length=150), nullable=True, comment="location_typeが'circuit'の場合のサーキット名"))
        batch_op.add_column(sa.Column('custom_location', sa.String(length=200), nullable=True, comment="location_typeが'custom'の場合の自由入力場所名"))
        batch_op.alter_column('location_name',
               existing_type=sa.VARCHAR(length=150),
               nullable=True)
        batch_op.create_index(batch_op.f('ix_activity_logs_circuit_name'), ['circuit_name'], unique=False)

    with op.batch_alter_table('session_logs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('best_lap_seconds', sa.Numeric(precision=8, scale=3), nullable=True, comment='このセッションでのベストラップ（秒）'))
        batch_op.add_column(sa.Column('include_in_leaderboard', sa.Boolean(), server_default='true', nullable=False, comment='この記録をリーダーボードに掲載するか'))
        batch_op.create_index(batch_op.f('ix_session_logs_best_lap_seconds'), ['best_lap_seconds'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('session_logs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_session_logs_best_lap_seconds'))
        batch_op.drop_column('include_in_leaderboard')
        batch_op.drop_column('best_lap_seconds')

    with op.batch_alter_table('activity_logs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_activity_logs_circuit_name'))
        batch_op.alter_column('location_name',
               existing_type=sa.VARCHAR(length=150),
               nullable=False)
        batch_op.drop_column('custom_location')
        batch_op.drop_column('circuit_name')
        batch_op.drop_column('location_type')
        batch_op.drop_column('activity_title')

    # ### end Alembic commands ###
