"""Add maintenance record link to reminders

Revision ID: 3f8fa3c5156e
Revises: d5b35174a1cb
Create Date: 2025-07-15 00:44:52.961104

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3f8fa3c5156e'
down_revision = 'd5b35174a1cb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('maintenance_reminders', schema=None) as batch_op:
        batch_op.add_column(sa.Column('last_maintenance_entry_id', sa.Integer(), nullable=True))
        batch_op.alter_column('task_description',
               existing_type=sa.VARCHAR(length=200),
               comment='リマインド内容/カテゴリ',
               existing_nullable=False)
        batch_op.alter_column('last_done_date',
               existing_type=sa.DATE(),
               comment='手動入力または連携された最終実施日',
               existing_nullable=True)
        batch_op.alter_column('last_done_km',
               existing_type=sa.INTEGER(),
               comment='手動入力または連携された最終実施距離',
               existing_nullable=True)
        batch_op.create_foreign_key(None, 'maintenance_entries', ['last_maintenance_entry_id'], ['id'], ondelete='SET NULL')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('maintenance_reminders', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.alter_column('last_done_km',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='手動入力または連携された最終実施距離',
               existing_nullable=True)
        batch_op.alter_column('last_done_date',
               existing_type=sa.DATE(),
               comment=None,
               existing_comment='手動入力または連携された最終実施日',
               existing_nullable=True)
        batch_op.alter_column('task_description',
               existing_type=sa.VARCHAR(length=200),
               comment=None,
               existing_comment='リマインド内容/カテゴリ',
               existing_nullable=False)
        batch_op.drop_column('last_maintenance_entry_id')

    # ### end Alembic commands ###
