"""Add Achievement and UserAchievement models

Revision ID: 414794921235
Revises: 5d18f0a4938e
Create Date: 2025-05-09 11:41:22.538499

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '414794921235' # あなたの環境で生成された実際のIDに置き換えてください
down_revision = '5d18f0a4938e' # これは正しいはずです
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('achievement_definitions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=100), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('icon_class', sa.String(length=100), nullable=True),
    sa.Column('category_code', sa.String(length=50), nullable=False),
    sa.Column('category_name', sa.String(length=100), nullable=False),
    sa.Column('share_text_template', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('achievement_definitions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_achievement_definitions_category_code'), ['category_code'], unique=False)
        batch_op.create_index(batch_op.f('ix_achievement_definitions_code'), ['code'], unique=True)

    op.create_table('user_achievements',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('achievement_code', sa.String(length=100), nullable=False),
    sa.Column('unlocked_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['achievement_code'], ['achievement_definitions.code'], name=op.f('fk_user_achievements_achievement_code_achievement_definitions'), ondelete='CASCADE'), # nameを追加
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_user_achievements_user_id_users'), ondelete='CASCADE'), # nameを追加
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'achievement_code', name='uq_user_achievement')
    )
    with op.batch_alter_table('user_achievements', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_achievements_achievement_code'), ['achievement_code'], unique=False)
        batch_op.create_index(batch_op.f('ix_user_achievements_user_id'), ['user_id'], unique=False)

    # ### end Alembic commands ###

    # ▼▼▼ 初期実績データの投入処理をここから追加 ▼▼▼
    achievement_definitions_table = sa.table(
        'achievement_definitions',
        sa.column('code', sa.String),
        sa.column('name', sa.String),
        sa.column('description', sa.Text),
        sa.column('icon_class', sa.String),
        sa.column('category_code', sa.String),
        sa.column('category_name', sa.String),
        sa.column('share_text_template', sa.Text)
    )

    op.bulk_insert(achievement_definitions_table, [
        {
            'code': 'FIRST_VEHICLE', 'name': '最初の相棒', 'description': '初めて車両を登録する',
            'icon_class': 'fas fa-car-side', 'category_code': 'vehicle', 'category_name': '車両関連',
            'share_text_template': '実績「{achievement_name}」を解除！初めての愛車を登録したよ！🏍️ #もとぷっぷー'
        },
        {
            'code': 'FIRST_FUEL_LOG', 'name': '給油デビュー', 'description': '初めて給油記録を追加する',
            'icon_class': 'fas fa-gas-pump', 'category_code': 'fuel', 'category_name': '給油記録',
            'share_text_template': '実績「{achievement_name}」を解除！初めて給油を記録！⛽ #もとぷっぷー'
        },
        {
            'code': 'FIRST_MAINT_LOG', 'name': '初メンテナンス', 'description': '初めて整備記録を追加する',
            'icon_class': 'fas fa-tools', 'category_code': 'maintenance', 'category_name': '整備記録',
            'share_text_template': '実績「{achievement_name}」を解除！初めて整備を記録！🔧 #もとぷっぷー'
        },
        {
            'code': 'FIRST_NOTE', 'name': '初めてのメモ', 'description': '初めてノートまたはタスクを記録する',
            'icon_class': 'fas fa-book', 'category_code': 'general', 'category_name': 'その他',
            'share_text_template': '実績「{achievement_name}」を解除！思い出やタスクを残したよ！📝 #もとぷっぷー'
        },
        {
            'code': 'FIRST_ODO_RESET', 'name': 'ODOリセット初体験', 'description': '初めてODOメーターのリセットを記録する',
            'icon_class': 'fas fa-undo', 'category_code': 'vehicle', 'category_name': '車両関連',
            'share_text_template': '実績「{achievement_name}」を解除！メーターリセットを体験！🔄 #もとぷっぷー'
        }
    ])
    # ▲▲▲ 初期実績データの投入処理ここまで ▲▲▲


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_achievements', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_achievements_user_id'))
        batch_op.drop_index(batch_op.f('ix_user_achievements_achievement_code'))
        # ForeignKeyConstraint の名前を指定して削除 (op.f() で生成された名前を使う)
        batch_op.drop_constraint(batch_op.f('fk_user_achievements_user_id_users'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('fk_user_achievements_achievement_code_achievement_definitions'), type_='foreignkey')


    op.drop_table('user_achievements')
    with op.batch_alter_table('achievement_definitions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_achievement_definitions_code'))
        batch_op.drop_index(batch_op.f('ix_achievement_definitions_category_code'))

    op.drop_table('achievement_definitions')
    # ### end Alembic commands ###