"""Add activity log models

Revision ID: 48c543b24155
Revises: 4bc80d3366bf
Create Date: 2025-07-04 15:25:48.006582

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '48c543b24155'
down_revision = '4bc80d3366bf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('session_logs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('session_duration_hours', sa.Numeric(precision=8, scale=2), nullable=True))
        batch_op.add_column(sa.Column('session_distance', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('session_logs', schema=None) as batch_op:
        batch_op.drop_column('session_distance')
        batch_op.drop_column('session_duration_hours')

    # ### end Alembic commands ###
