"""Add activity log models

Revision ID: 4bc80d3366bf
Revises: 3c3d01d7c4c9
Create Date: 2025-07-04 13:41:21.093154

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '4bc80d3366bf'
down_revision = '3c3d01d7c4c9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('activity_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('motorcycle_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('activity_date', sa.Date(), nullable=False),
    sa.Column('location_name', sa.String(length=150), nullable=False),
    sa.Column('weather', sa.String(length=50), nullable=True),
    sa.Column('temperature', sa.Numeric(precision=4, scale=1), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['motorcycle_id'], ['motorcycles.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('activity_logs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_activity_logs_activity_date'), ['activity_date'], unique=False)

    op.create_table('setting_sheets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('motorcycle_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('sheet_name', sa.String(length=100), nullable=False),
    sa.Column('details', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('is_archived', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['motorcycle_id'], ['motorcycles.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('setting_sheets', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_setting_sheets_sheet_name'), ['sheet_name'], unique=False)

    op.create_table('session_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('activity_log_id', sa.Integer(), nullable=False),
    sa.Column('setting_sheet_id', sa.Integer(), nullable=True),
    sa.Column('session_name', sa.String(length=100), nullable=True),
    sa.Column('lap_times', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('rider_feel', sa.Text(), nullable=True),
    sa.Column('operating_hours_start', sa.Numeric(precision=8, scale=2), nullable=True),
    sa.Column('operating_hours_end', sa.Numeric(precision=8, scale=2), nullable=True),
    sa.Column('odo_start', sa.Integer(), nullable=True),
    sa.Column('odo_end', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['activity_log_id'], ['activity_logs.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['setting_sheet_id'], ['setting_sheets.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('session_logs')
    with op.batch_alter_table('setting_sheets', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_setting_sheets_sheet_name'))

    op.drop_table('setting_sheets')
    with op.batch_alter_table('activity_logs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_activity_logs_activity_date'))

    op.drop_table('activity_logs')
    # ### end Alembic commands ###
