"""add comment column to event_participant

Revision ID: 572a08fb9691
Revises: eb1d1f1f5d2a
Create Date: 2025-11-20 11:31:26.844589

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '572a08fb9691'
down_revision = 'eb1d1f1f5d2a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('event_participants', schema=None) as batch_op:
        batch_op.add_column(sa.Column('comment', sa.String(length=100), nullable=True, comment='参加者の一言コメント'))

    with op.batch_alter_table('motorcycles', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_motorcycles_is_archived'))
        batch_op.drop_column('is_archived')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('motorcycles', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_archived', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False, comment='アーカイブ済みフラグ'))
        batch_op.create_index(batch_op.f('ix_motorcycles_is_archived'), ['is_archived'], unique=False)

    with op.batch_alter_table('event_participants', schema=None) as batch_op:
        batch_op.drop_column('comment')

    # ### end Alembic commands ###
