"""Add user_id to event_participants

Revision ID: 577352be52cc
Revises: 856cf992fcd9
Create Date: 2025-11-22 13:06:27.318107

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '577352be52cc'
down_revision = '856cf992fcd9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('event_participants', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.Integer(), nullable=True, comment='紐づくユーザーID'))
        batch_op.create_index(batch_op.f('ix_event_participants_user_id'), ['user_id'], unique=False)
        batch_op.create_foreign_key(None, 'users', ['user_id'], ['id'], ondelete='SET NULL')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('event_participants', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_event_participants_user_id'))
        batch_op.drop_column('user_id')

    # ### end Alembic commands ###
