"""Add use_lite_dashboard column to users table

Revision ID: 661acfdfe77c
Revises: 19f355eab962
Create Date: 2026-01-28 00:57:06.984297

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '661acfdfe77c'
down_revision = '19f355eab962'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('use_lite_dashboard', sa.Boolean(), server_default='false', nullable=False, comment='ログイン時に軽量ダッシュボードを表示するか'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('use_lite_dashboard')

    # ### end Alembic commands ###
