"""Add event_notifications table

Revision ID: 6822ab0afd37
Revises: b65e4ac8be35
Create Date: 2026-04-14 12:54:11.997945

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6822ab0afd37'
down_revision = 'b65e4ac8be35'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('event_notifications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('event_id', sa.Integer(), nullable=False),
    sa.Column('notification_type', sa.String(length=50), nullable=False, comment="通知タイプ (例: '60days', '30days', '14days', '7days', '3days', '1day', 'today')"),
    sa.Column('misskey_note_id', sa.String(length=32), nullable=True, comment='投稿のノートID'),
    sa.Column('posted_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('event_id', 'notification_type', name='uq_event_notification_type')
    )
    with op.batch_alter_table('event_notifications', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_event_notifications_event_id'), ['event_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('event_notifications', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_event_notifications_event_id'))

    op.drop_table('event_notifications')
    # ### end Alembic commands ###
