"""Add racer fields to Motorcycle

Revision ID: 6dadc8ff0649
Revises: 760969e7b61d
Create Date: 2025-05-11 13:23:01.781756

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6dadc8ff0649'
down_revision = '760969e7b61d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('motorcycles', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_racer', sa.Boolean(), server_default='false', nullable=False))
        batch_op.add_column(sa.Column('total_operating_hours', sa.Numeric(precision=8, scale=2), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('motorcycles', schema=None) as batch_op:
        batch_op.drop_column('total_operating_hours')
        batch_op.drop_column('is_racer')

    # ### end Alembic commands ###
