"""Add dashboard_layout to User model

Revision ID: 7b1844b671ec
Revises: 672787e0972f
Create Date: 2025-08-07 02:56:43.230071

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7b1844b671ec'
down_revision = '672787e0972f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('dashboard_layout', sa.JSON(), nullable=True, comment='ダッシュボードのウィジェットの並び順'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('dashboard_layout')

    # ### end Alembic commands ###
