"""add vehicle_name to event_participant

Revision ID: 856cf992fcd9
Revises: 572a08fb9691
Create Date: 2025-11-20 11:48:20.826170

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '856cf992fcd9'
down_revision = '572a08fb9691'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('event_participants', schema=None) as batch_op:
        batch_op.add_column(sa.Column('vehicle_name', sa.String(length=50), nullable=True, comment='参加車両名'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('event_participants', schema=None) as batch_op:
        batch_op.drop_column('vehicle_name')

    # ### end Alembic commands ###
