"""Re-design garage card to be user-centric

Revision ID: 890e7eb7d568
Revises: 37af33cd44be
Create Date: 2025-08-07 23:23:18.483642

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '890e7eb7d568'
down_revision = '37af33cd44be'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('motorcycles', schema=None) as batch_op:
        batch_op.add_column(sa.Column('show_in_garage', sa.Boolean(), server_default='true', nullable=False, comment='ガレージカードに掲載するか'))
        batch_op.drop_index(batch_op.f('ix_motorcycles_public_id'))
        batch_op.drop_column('is_public')
        batch_op.drop_column('public_id')

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('public_id', sa.String(length=36), nullable=True, comment='公開ガレージ用の一意なID'))
        batch_op.add_column(sa.Column('is_garage_public', sa.Boolean(), server_default='false', nullable=False, comment='ガレージカードを公開するか'))
        batch_op.create_index(batch_op.f('ix_users_public_id'), ['public_id'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_public_id'))
        batch_op.drop_column('is_garage_public')
        batch_op.drop_column('public_id')

    with op.batch_alter_table('motorcycles', schema=None) as batch_op:
        batch_op.add_column(sa.Column('public_id', sa.VARCHAR(length=36), autoincrement=False, nullable=True, comment='公開用の一意なID'))
        batch_op.add_column(sa.Column('is_public', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False, comment='ガレージカードを公開するか'))
        batch_op.create_index(batch_op.f('ix_motorcycles_public_id'), ['public_id'], unique=True)
        batch_op.drop_column('show_in_garage')

    # ### end Alembic commands ###
