"""add_odo_reset_log_table_and_data_migration

Revision ID: 896791ff77ea
Revises: cb61b6485ca8
Create Date: 2025-05-06 14:21:50.148204

"""
from alembic import op
import sqlalchemy as sa
from datetime import date, datetime


# revision identifiers, used by Alembic.
revision = '896791ff77ea'
down_revision = 'cb61b6485ca8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('odo_reset_logs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('display_odo_before_reset', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('display_odo_after_reset', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('offset_increment', sa.Integer(), nullable=False))
        batch_op.drop_column('offset_change')
        batch_op.drop_column('odometer_before_reset')
        batch_op.drop_column('odometer_after_reset')

    # ### end Alembic commands ###

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('odo_reset_logs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('odometer_after_reset', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('odometer_before_reset', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('offset_change', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.drop_column('offset_increment')
        batch_op.drop_column('display_odo_after_reset')
        batch_op.drop_column('display_odo_before_reset')

    # ### end Alembic commands ###
