"""Add show_cost_in_dashboard to User model

Revision ID: 8fa81400776d
Revises: 890e7eb7d568
Create Date: 2025-08-08 12:33:29.278274

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8fa81400776d'
down_revision = '890e7eb7d568'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('show_cost_in_dashboard', sa.Boolean(), server_default='true', nullable=False, comment='ダッシュボードでコスト関連情報を表示するか'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('show_cost_in_dashboard')

    # ### end Alembic commands ###
