"""Add gps_tracks to SessionLog

Revision ID: 8ffa50023b83
Revises: e391d758c56d
Create Date: 2025-08-25 00:48:25.016555

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '8ffa50023b83'
down_revision = 'e391d758c56d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('session_logs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('gps_tracks', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='ラップごとのGPS軌跡データ'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('session_logs', schema=None) as batch_op:
        batch_op.drop_column('gps_tracks')

    # ### end Alembic commands ###
