"""add team_id to event model

Revision ID: 92c294d8d5dd
Revises: 577352be52cc
Create Date: 2025-11-23 01:40:29.405070

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '92c294d8d5dd'
down_revision = '577352be52cc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('events', schema=None) as batch_op:
        batch_op.add_column(sa.Column('team_id', sa.Integer(), nullable=True, comment='チームイベントの場合のチームID'))
        batch_op.create_index(batch_op.f('ix_events_team_id'), ['team_id'], unique=False)
        batch_op.create_foreign_key(None, 'teams', ['team_id'], ['id'], ondelete='CASCADE')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('events', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_events_team_id'))
        batch_op.drop_column('team_id')

    # ### end Alembic commands ###
