"""Add event and event_participant models

Revision ID: 9516bc768302
Revises: df2ec8ec945c
Create Date: 2025-07-15 07:23:14.427454

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9516bc768302'
down_revision = 'df2ec8ec945c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('public_id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False, comment='イベント作成者のID'),
    sa.Column('motorcycle_id', sa.Integer(), nullable=True, comment='関連する車両のID'),
    sa.Column('title', sa.String(length=200), nullable=False, comment='イベント名'),
    sa.Column('description', sa.Text(), nullable=True, comment='イベントの詳細説明'),
    sa.Column('location', sa.String(length=200), nullable=True, comment='開催場所'),
    sa.Column('start_datetime', sa.DateTime(), nullable=False, comment='開始日時 (UTC)'),
    sa.Column('end_datetime', sa.DateTime(), nullable=True, comment='終了日時 (UTC)'),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['motorcycle_id'], ['motorcycles.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('events', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_events_public_id'), ['public_id'], unique=True)

    op.create_table('event_participants',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('event_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False, comment='参加者名'),
    sa.Column('status', sa.Enum('attending', 'tentative', 'not_attending', name='participationstatus'), nullable=False, comment='出欠ステータス'),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('event_id', 'name', name='uq_event_participant_name')
    )
    with op.batch_alter_table('event_participants', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_event_participants_event_id'), ['event_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('event_participants', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_event_participants_event_id'))

    op.drop_table('event_participants')
    with op.batch_alter_table('events', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_events_public_id'))

    op.drop_table('events')
    # ### end Alembic commands ###
