"""add use_beta_ui to users

Revision ID: a656f6292a19
Revises: d63a8490b40f
Create Date: 2026-04-13 10:09:31.013688

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a656f6292a19'
down_revision = 'd63a8490b40f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('use_beta_ui', sa.Boolean(), server_default='false', nullable=False, comment='Beta UI（ダークテーマ）を使用するか'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('use_beta_ui')

    # ### end Alembic commands ###
