"""Add encrypted_misskey_api_token to User model

Revision ID: aa6d3aff4f5c
Revises: 2611ecc6c187
Create Date: 2025-07-17 01:03:08.882271

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'aa6d3aff4f5c'
down_revision = '2611ecc6c187'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('touring_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('motorcycle_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('touring_date', sa.Date(), nullable=False),
    sa.Column('memo', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['motorcycle_id'], ['motorcycles.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('touring_logs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_touring_logs_motorcycle_id'), ['motorcycle_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_touring_logs_touring_date'), ['touring_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_touring_logs_user_id'), ['user_id'], unique=False)

    op.create_table('touring_scrapbook_entries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('touring_log_id', sa.Integer(), nullable=False),
    sa.Column('misskey_note_id', sa.String(length=32), nullable=False),
    sa.ForeignKeyConstraint(['touring_log_id'], ['touring_logs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('touring_log_id', 'misskey_note_id', name='uq_touring_log_note')
    )
    with op.batch_alter_table('touring_scrapbook_entries', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_touring_scrapbook_entries_misskey_note_id'), ['misskey_note_id'], unique=False)

    op.create_table('touring_spots',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('touring_log_id', sa.Integer(), nullable=False),
    sa.Column('spot_name', sa.String(length=150), nullable=False),
    sa.Column('memo', sa.Text(), nullable=True),
    sa.Column('order', sa.Integer(), nullable=False, comment='スポットの順序'),
    sa.Column('photo_link_url', sa.String(length=2048), nullable=True, comment='外部の写真URL'),
    sa.ForeignKeyConstraint(['touring_log_id'], ['touring_logs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('touring_spots', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_touring_spots_touring_log_id'), ['touring_log_id'], unique=False)

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('encrypted_misskey_api_token', sa.Text(), nullable=True, comment='暗号化されたMisskey APIトークン'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('encrypted_misskey_api_token')

    with op.batch_alter_table('touring_spots', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_touring_spots_touring_log_id'))

    op.drop_table('touring_spots')
    with op.batch_alter_table('touring_scrapbook_entries', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_touring_scrapbook_entries_misskey_note_id'))

    op.drop_table('touring_scrapbook_entries')
    with op.batch_alter_table('touring_logs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_touring_logs_user_id'))
        batch_op.drop_index(batch_op.f('ix_touring_logs_touring_date'))
        batch_op.drop_index(batch_op.f('ix_touring_logs_motorcycle_id'))

    op.drop_table('touring_logs')
    # ### end Alembic commands ###
