"""Add VehicleCategory model and display_order/vehicle_category_id to Motorcycle

Revision ID: b65e4ac8be35
Revises: a656f6292a19
Create Date: 2026-04-14 05:05:16.677663

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b65e4ac8be35'
down_revision = 'a656f6292a19'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('vehicle_categories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False, comment='カテゴリ名 (例: サーキット用, オフロード)'),
    sa.Column('display_order', sa.Integer(), server_default='0', nullable=False, comment='カテゴリの表示順序'),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'name', name='uq_user_vehicle_category_name')
    )
    with op.batch_alter_table('vehicle_categories', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_vehicle_categories_user_id'), ['user_id'], unique=False)

    with op.batch_alter_table('motorcycles', schema=None) as batch_op:
        batch_op.add_column(sa.Column('vehicle_category_id', sa.Integer(), nullable=True, comment='所属カテゴリID (NULLは未分類)'))
        batch_op.add_column(sa.Column('display_order', sa.Integer(), server_default='0', nullable=False, comment='カテゴリ内の表示順序'))
        batch_op.create_index(batch_op.f('ix_motorcycles_vehicle_category_id'), ['vehicle_category_id'], unique=False)
        batch_op.create_foreign_key(None, 'vehicle_categories', ['vehicle_category_id'], ['id'], ondelete='SET NULL')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('motorcycles', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_motorcycles_vehicle_category_id'))
        batch_op.drop_column('display_order')
        batch_op.drop_column('vehicle_category_id')

    with op.batch_alter_table('vehicle_categories', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_vehicle_categories_user_id'))

    op.drop_table('vehicle_categories')
    # ### end Alembic commands ###
