"""Add garage_theme and hero_vehicle_id to User model

Revision ID: be856a8078da
Revises: 8fa81400776d
Create Date: 2025-08-09 19:58:33.189437

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'be856a8078da'
down_revision = '8fa81400776d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('garage_theme', sa.String(length=50), server_default='default', nullable=False, comment='ガレージカードのデザインテーマ'))
        batch_op.add_column(sa.Column('garage_hero_vehicle_id', sa.Integer(), nullable=True, comment='ガレージの主役車両ID'))
        batch_op.create_foreign_key(None, 'motorcycles', ['garage_hero_vehicle_id'], ['id'], ondelete='SET NULL')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('garage_hero_vehicle_id')
        batch_op.drop_column('garage_theme')

    # ### end Alembic commands ###
