"""Add UserCircuitTarget model for target lap times

Revision ID: bf41f9654c05
Revises: 309af67c371a
Create Date: 2025-09-11 11:37:52.777724

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bf41f9654c05'
down_revision = '309af67c371a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_circuit_targets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('circuit_name', sa.String(length=150), nullable=False),
    sa.Column('target_lap_seconds', sa.Numeric(precision=8, scale=3), nullable=False, comment='目標ラップタイム（秒）'),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'circuit_name', name='uq_user_circuit_target')
    )
    with op.batch_alter_table('user_circuit_targets', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_circuit_targets_circuit_name'), ['circuit_name'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_circuit_targets', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_circuit_targets_circuit_name'))

    op.drop_table('user_circuit_targets')
    # ### end Alembic commands ###
