"""Add nyanpuppu_simple_mode to User model

Revision ID: c24550546f19
Revises: 008bd7bcf7a1
Create Date: 2025-10-16 02:21:40.685853

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c24550546f19'
down_revision = '008bd7bcf7a1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('nyanpuppu_simple_mode', sa.Boolean(), server_default='false', nullable=False, comment='にゃんぷっぷーの知能を取り上げるか'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('nyanpuppu_simple_mode')

    # ### end Alembic commands ###
