"""Add passcode_hash to event_participants

Revision ID: c9271122696a
Revises: 6a92e8863546
Create Date: 2025-07-15 09:31:50.416930

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c9271122696a'
down_revision = '6a92e8863546'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('event_participants', schema=None) as batch_op:
        batch_op.add_column(sa.Column('passcode_hash', sa.String(length=255), nullable=True, comment='出欠変更用のパスコードのハッシュ'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('event_participants', schema=None) as batch_op:
        batch_op.drop_column('passcode_hash')

    # ### end Alembic commands ###
