"""Initial migration.

Revision ID: cbc2495d2f76
Revises: 
Create Date: 2025-05-03 19:54:00.472318

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cbc2495d2f76'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('misskey_user_id', sa.String(length=100), nullable=False),
    sa.Column('misskey_username', sa.String(length=100), nullable=True),
    sa.Column('is_admin', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('misskey_user_id')
    )
    op.create_table('motorcycles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('maker', sa.String(length=80), nullable=True),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('year', sa.Integer(), nullable=True),
    sa.Column('odometer_offset', sa.Integer(), nullable=False),
    sa.Column('is_default', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('consumable_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('motorcycle_id', sa.Integer(), nullable=False),
    sa.Column('type', sa.String(length=20), nullable=False),
    sa.Column('change_date', sa.Date(), nullable=False),
    sa.Column('total_distance_at_change', sa.Integer(), nullable=False),
    sa.Column('brand_name', sa.String(length=100), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['motorcycle_id'], ['motorcycles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('fuel_entries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('motorcycle_id', sa.Integer(), nullable=False),
    sa.Column('entry_date', sa.Date(), nullable=False),
    sa.Column('odometer_reading', sa.Integer(), nullable=False),
    sa.Column('total_distance', sa.Integer(), nullable=False),
    sa.Column('fuel_volume', sa.Float(), nullable=False),
    sa.Column('price_per_liter', sa.Float(), nullable=True),
    sa.Column('total_cost', sa.Float(), nullable=True),
    sa.Column('station_name', sa.String(length=100), nullable=True),
    sa.Column('fuel_type', sa.String(length=20), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('is_full_tank', sa.Boolean(), server_default='1', nullable=False),
    sa.ForeignKeyConstraint(['motorcycle_id'], ['motorcycles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('maintenance_entries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('motorcycle_id', sa.Integer(), nullable=False),
    sa.Column('maintenance_date', sa.Date(), nullable=False),
    sa.Column('odometer_reading_at_maintenance', sa.Integer(), nullable=False),
    sa.Column('total_distance_at_maintenance', sa.Integer(), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('location', sa.String(length=100), nullable=True),
    sa.Column('parts_cost', sa.Float(), nullable=True),
    sa.Column('labor_cost', sa.Float(), nullable=True),
    sa.Column('category', sa.String(length=50), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['motorcycle_id'], ['motorcycles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('maintenance_reminders',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('motorcycle_id', sa.Integer(), nullable=False),
    sa.Column('task_description', sa.String(length=200), nullable=False),
    sa.Column('interval_km', sa.Integer(), nullable=True),
    sa.Column('interval_months', sa.Integer(), nullable=True),
    sa.Column('last_done_date', sa.Date(), nullable=True),
    sa.Column('last_done_km', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['motorcycle_id'], ['motorcycles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('attachments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('maintenance_entry_id', sa.Integer(), nullable=False),
    sa.Column('filename', sa.String(length=255), nullable=False),
    sa.Column('filepath', sa.String(length=512), nullable=False),
    sa.Column('upload_date', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['maintenance_entry_id'], ['maintenance_entries.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('filepath')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('attachments')
    op.drop_table('maintenance_reminders')
    op.drop_table('maintenance_entries')
    op.drop_table('fuel_entries')
    op.drop_table('consumable_logs')
    op.drop_table('motorcycles')
    op.drop_table('users')
    # ### end Alembic commands ###
