"""Add snooze and dismiss fields to MaintenanceReminder

Revision ID: cd3f0707d765
Revises: 2b2e0801467f
Create Date: 2025-10-04 04:48:07.110657

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cd3f0707d765'
down_revision = '2b2e0801467f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('maintenance_reminders', schema=None) as batch_op:
        batch_op.add_column(sa.Column('snoozed_until', sa.DateTime(), nullable=True, comment='スヌーズ期限 (UTC)'))
        batch_op.add_column(sa.Column('is_dismissed', sa.Boolean(), server_default='false', nullable=False, comment='非表示フラグ'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('maintenance_reminders', schema=None) as batch_op:
        batch_op.drop_column('is_dismissed')
        batch_op.drop_column('snoozed_until')

    # ### end Alembic commands ###
