"""Check sync after fixing relationship

Revision ID: cd7db2474a21
Revises: cbc2495d2f76
Create Date: 2025-05-05 15:01:30.214661

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cd7db2474a21'
down_revision = 'cbc2495d2f76'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('motorcycles', schema=None) as batch_op:
        # 既存の外部キー制約を削除
        batch_op.drop_constraint('motorcycles_user_id_fkey', type_='foreignkey')
        # ondelete='CASCADE' 付きで外部キー制約を再作成
        batch_op.create_foreign_key(None, 'users', ['user_id'], ['id'], ondelete='CASCADE')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('motorcycles', schema=None) as batch_op:
        # CASCADE付きの制約を削除
        batch_op.drop_constraint(None, type_='foreignkey')
        # 元の（CASCADEなしの）制約を再作成
        batch_op.create_foreign_key('motorcycles_user_id_fkey', 'users', ['user_id'], ['id'])

    # ### end Alembic commands ###