"""Add share_with_teams to ActivityLog

Revision ID: cd8c6f685e48
Revises: 65cb43e34218
Create Date: 2025-09-11 13:34:28.216360

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cd8c6f685e48'
down_revision = '65cb43e34218'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('activity_logs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('share_with_teams', sa.Boolean(), server_default='false', nullable=False, comment='この活動ログを所属チームに共有するか'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('activity_logs', schema=None) as batch_op:
        batch_op.drop_column('share_with_teams')

    # ### end Alembic commands ###
