"""add operating_hours_at_maintenance

Revision ID: d3c34cc7dbaa
Revises: eba867fbba3c
Create Date: 2026-03-10 03:32:23.563614

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd3c34cc7dbaa'
down_revision = 'eba867fbba3c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('maintenance_entries', schema=None) as batch_op:
        batch_op.add_column(sa.Column('operating_hours_at_maintenance', sa.Numeric(precision=8, scale=2), nullable=True, comment='レーサー車両用の稼働時間'))
        batch_op.alter_column('odometer_reading_at_maintenance',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('maintenance_entries', schema=None) as batch_op:
        batch_op.alter_column('odometer_reading_at_maintenance',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.drop_column('operating_hours_at_maintenance')

    # ### end Alembic commands ###
