"""Add is_odo_pending to FuelEntry and MaintenanceEntry

Revision ID: d63a8490b40f
Revises: d3c34cc7dbaa
Create Date: 2026-03-31 03:31:04.418204

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd63a8490b40f'
down_revision = 'd3c34cc7dbaa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('fuel_entries', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_odo_pending', sa.Boolean(), server_default='false', nullable=False, comment='ODO入力保留フラグ'))

    with op.batch_alter_table('maintenance_entries', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_odo_pending', sa.Boolean(), server_default='false', nullable=False, comment='ODO/稼働時間入力保留フラグ'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('maintenance_entries', schema=None) as batch_op:
        batch_op.drop_column('is_odo_pending')

    with op.batch_alter_table('fuel_entries', schema=None) as batch_op:
        batch_op.drop_column('is_odo_pending')

    # ### end Alembic commands ###
