"""Add public share fields to SessionLog

Revision ID: e41c7c921b61
Revises: 8ffa50023b83
Create Date: 2025-08-25 04:41:34.361745

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e41c7c921b61'
down_revision = '8ffa50023b83'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('session_logs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('public_share_token', sa.String(length=36), nullable=True, comment='外部共有用の一意なトークン (UUID)'))
        batch_op.add_column(sa.Column('is_public', sa.Boolean(), server_default='false', nullable=False, comment='このセッションを外部共有するか'))
        batch_op.create_index(batch_op.f('ix_session_logs_public_share_token'), ['public_share_token'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('session_logs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_session_logs_public_share_token'))
        batch_op.drop_column('is_public')
        batch_op.drop_column('public_share_token')

    # ### end Alembic commands ###
