"""Add is_archived to Motorcycle

Revision ID: eb1d1f1f5d2a
Revises: c24550546f19
Create Date: 2025-10-20 01:45:05.366599

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'eb1d1f1f5d2a'
down_revision = 'c24550546f19'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('motorcycles', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_archived', sa.Boolean(), server_default='false', nullable=False, comment='アーカイブ済みフラグ'))
        batch_op.create_index(batch_op.f('ix_motorcycles_is_archived'), ['is_archived'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('motorcycles', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_motorcycles_is_archived'))
        batch_op.drop_column('is_archived')

    # ### end Alembic commands ###
