"""add is_archived to motorcycle

Revision ID: eba867fbba3c
Revises: 079d7fe7cb3e
Create Date: 2026-03-10 01:50:29.851957

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'eba867fbba3c'
down_revision = '079d7fe7cb3e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('motorcycles', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_archived', sa.Boolean(), server_default='false', nullable=False, comment='アーカイブされた車両'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('motorcycles', schema=None) as batch_op:
        batch_op.drop_column('is_archived')

    # ### end Alembic commands ###
