"""Add auto_update_from_category to reminders

Revision ID: f0c7fc2c92ad
Revises: 3f8fa3c5156e
Create Date: 2025-07-15 04:02:03.882881

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f0c7fc2c92ad'
down_revision = '3f8fa3c5156e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('maintenance_reminders', schema=None) as batch_op:
        batch_op.add_column(sa.Column('auto_update_from_category', sa.Boolean(), server_default='true', nullable=False, comment='カテゴリ名が一致した整備記録で自動更新するか'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('maintenance_reminders', schema=None) as batch_op:
        batch_op.drop_column('auto_update_from_category')

    # ### end Alembic commands ###
